(coq.theory
 (name ReadFile_Perf)
 (theories ReadFile)
 (plugins rocq-read-file.plugin))

(copy_files ../data/*.bin)
(copy_files ../data/*.txt)

; Work around missing dune support for Extra Dependency.
; https://github.com/ocaml/dune/pull/9591
; This generates a dummy .v whose content changes when any data file
; changes, forcing dune to rebuild dependent theories.
(rule
 (target dep_hashes.v)
 (deps
  (glob_files ../data/*.bin)
  (glob_files ../data/*.txt))
 (action
  (with-stdout-to %{target}
   (run rocq-read-file-shafile %{deps}))))
