(library
 (name read_file_plugin)
 (public_name rocq-read-file.plugin)
 (synopsis "Read files into Rocq as primitive arrays / strings")
 (flags :standard -rectypes -w -27-32-33-39)
 (libraries rocq-runtime.plugins.ltac)
 (preprocess (pps ppx_optcomp -- -cookie "ppx_optcomp.env=env ~coq:(Defined \"%{rocq:version.major}.%{rocq:version.minor}\")")))

(rocq.pp (modules g_read_file))
