name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - coq_version: '8.20'
            ocaml_version: '4.14-flambda'
          - coq_version: '9.0'
            ocaml_version: '4.14-flambda'
          - coq_version: '9.1'
            ocaml_version: '4.14-flambda'
          - coq_version: '9.2'
            ocaml_version: '4.14-flambda'
          - coq_version: 'dev'
            ocaml_version: '4.14-flambda'

    runs-on: ubuntu-latest
    container:
      image: coqorg/coq:${{ matrix.coq_version }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate test data
        run: |
          chmod +x tests/gen.sh
          tests/gen.sh

      - name: Build
        run: |
          eval $(opam env)
          dune build

  build-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        if: hashFiles('flake.nix') != ''
      - name: Build with Nix
        if: hashFiles('flake.nix') != ''
        run: nix build
