name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        coq_version: ['8.20', '9.0', '9.1', '9.2']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate test data
        run: bash tests/gen.sh

      - uses: rocq-prover/docker-opam-action@master
        with:
          coq_version: ${{ matrix.coq_version }}
          before_install: |
            startGroup "Workaround git dubious ownership"
              git config --global --add safe.directory /github/workspace
            endGroup
            startGroup "Print opam config"
              opam config list; opam repo list; opam list
            endGroup
          script: |
            startGroup "Build"
              opam exec -- dune build
            endGroup
          uninstall: ''
